### ISSUE TITLE
incorrect requires version in version.php

### ISSUE THREAD

**Issue by danmarsden** [duitkupg/moodle-paygw_duitku#1]
https://github.com/duitkupg/moodle-paygw_duitku/blob/main/version.php#L31

This suggests that your plugin supports Moodle 3.0 and higher, but Moodle's payment gateways didn't land until Moodle 3.11 so this should be set to the requires version for Moodle 3.11

note this is a blocker for plugins db approval

**Comment by KangLeian** [comment]
Noted, thank you for your notification.

**Comment by danmarsden** [comment]
this doesn't appear to have been fixed? - and as mentioned, this is a blocker for approval.

**Comment by KangLeian** [comment]
Hei @danmarsden , The suggested plugin support has been set to 3.11 on the moodle suggestion version page. 
![image](https://user-images.githubusercontent.com/62584211/181433368-461746c9-a2d5-42cc-aab9-935fa627e2d2.png)
is it correct?

**Comment by danmarsden** [comment]
No.. see the link I pasted above. It's incorrect in your version.php file.

**Comment by danmarsden** [comment]
For more info see https://moodledev.io/docs/apis/commonfiles/version.php#requirements

**Comment by KangLeian** [comment]
We've updated the required version #29 
I'm sorry for my miss understanding.
It's should be this right?

**Comment by danmarsden** [comment]
no worries - that's it! - nice work :-)
