### ISSUE TITLE
Dissapear at Enrollment Method

### ISSUE THREAD

**Issue by krisnn** [duitkupg/moodle-paygw_duitku#24]
i has been follow the instruction at https://docs.duitku.com/payment-gateway/plugin/#tab_duitkupop , to install the plugin
but after i want add the enroll payment method, duitku not appear on list
![duitku_tidakmuncul](https://user-images.githubusercontent.com/44360893/181184280-60734449-c9c0-4cd6-bbd3-9f93c8391d62.png)

Using Moodle Moodle 4.0.1+ (Build: 20220701)

**Comment by KangLeian** [comment]
Hi @krisnn 
Did you install the enroll_duitku or paygw_duitku plugin type?
Have you followed the right plugin instruction on the doc https://docs.duitku.com/payment-gateway/plugin/#tab_duitkupop ?

**Comment by krisnn** [comment]
paygw_duitku,

yes, i follow the instruction on the doc

**Comment by KangLeian** [comment]
If you're using paygw_duitku you need to make sure it was enabled on the payment gateway plugin(**Site administrator ➜ Plugins ➜ Payment gateways ➜ Manage payment gateways**) and set on the payment account(**Site administrator ➜ General ➜ Payments ➜ Payment accounts**). 
On the enrolment course you should found your payment account name.

**Comment by KangLeian** [comment]
If you're using paygw_duitku you need to make sure it was enabled on the payment gateway plugin(**Site administrator ➜ Plugins ➜ Payment gateways ➜ Manage payment gateways**) and set on the payment account(**Site administrator ➜ General ➜ Payments ➜ Payment accounts**). 
On the enrolment course you should found your payment account name.

**Comment by krisnn** [comment]
yes i has been follow your instruction and that document, this my setting screenshoot and it was config same like documentation
pic 1
![1 enable](https://user-images.githubusercontent.com/44360893/181435487-0aea3c57-b6ec-41d7-bba2-9bfdda2a19b3.png)

pic 2
![2](https://user-images.githubusercontent.com/44360893/181435557-cec2ec94-e2ed-4a59-9ddc-5f19c6ba6bd7.png)

pic 3
![3](https://user-images.githubusercontent.com/44360893/181435584-771e90aa-2a8a-44f4-b22a-ee5cf4384d7d.png)

pic 4
![4](https://user-images.githubusercontent.com/44360893/181435601-0b27dab5-ccf9-45cb-a0f7-13b8dcd2bcfe.png)

**Comment by KangLeian** [comment]
Is your **enrolment on payment** active?
you should find at **Site administrator ➜ Plugins ➜ Enrolments ➜ Manage enrol plugins**

**Comment by krisnn** [comment]
yes has been active, and has been appear
i am wrong to see plugin active or not at Manage enrol plugins, maybe the team can rename it from Enrolment on payment to another. like add Duitku on last word "Enrolment on payment Duitku"

thanks for your help .. cheers
