### ISSUE TITLE
consider adding github actions support.

### ISSUE THREAD

**Issue by danmarsden** [duitkupg/moodle-paygw_duitku#3]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by maikdi** [comment]
@danmarsden Is it alright if I make a modifications to the moodle-plugin-ci codechecker test? Specifically the --max-warnings 0 part? All the codes return no error but only warnings for having line codes that are long (around 160 chars).

**Comment by danmarsden** [comment]
definitely! - full compliance is not a blocker for approval with the plugins db - it's just a really good tool that helps you improve code quality and maintain it once you manage to get most of your tests passing :-)
