### ISSUE TITLE
Peformance issue on footer hooks

### ISSUE THREAD

**Issue by danmarsden** [duitkupg/moodle-paygw_duitku#8]
Doing this on every single page load in the footer is quite nasty:
https://github.com/duitkupg/moodle-paygw_duitku/blob/main/lib.php#L35-L51

it has the potential to add quite a few db queries to every single page load on the site - even when your plugin is not in use. You should find a better way to implement this that does not impact on site performance - it should not be checking this on every single page load in the site.

**Comment by danmarsden** [comment]
I see you've added a check to see if it's enabled but you are still triggering this on every single pageload on the site. at the very least you should only run it on the homepage, or the users dashboard page but I'd prefer to not see this hook in the footer callback at all.

**Comment by maikdi** [comment]
Alright. The plugin will not be using the footer callback anymore, and will now use the message API as seen in #28. That shouldn't be a problem right?

**Comment by danmarsden** [comment]
that's a much cleaner solution - great work! :-)
